---
- name: web server install
  hosts: localhost
  become: true
  gather_facts: true

  tasks:

   - name: Install apache.
     yum:
      name:
       - yum-plugin-fastestmirror
       - epel-release
       - httpd
       - policycoreutils-python

      state: latest

   - name: Start service httpd, if not started
     service:
       name: httpd       
       state: started
       enabled: yes

   - name: Install remi.
     yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

   - name: enable remi-php72
     shell: yum-config-manager --enable remi-php72

   - name: Install php.
     yum:
      name:
       - php
       - php-common
       - php-mysqli
       - php-mysqlnd
       - php-pgsql
       - php-pear
       - php-mcrypt
       - php-cli
       - php-gd
       - php-curl
       - php-mbstring
       - php-xmlrpc
       - php-soap
       - php-ldap 
       - php-zip 
       - php-fileinfo 
       - php-xml 
       - php-intl
       - php-redis
      state: latest
      update_cache: yes
 
   - name: Replace apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'DirectoryIndex index.html'
       replace: 'DirectoryIndex index.php index.html index.htm'
     notify:
       - restart httpd

   - name: Replace php config
     replace:
       path: /etc/php.ini
       regexp: 'session.save_handler = files'
       replace: 'session.save_handler = redis'
  
   - name: Replace php config
     replace:
       path: /etc/php.ini
       regexp: ';session.save_path = \"/tmp\"'
       replace: 'session.save_path = "tcp://10.0.0.4:6379"'

   - name: Extract moodle-latest-36.tgz into /var/www/html
     unarchive:
       src: https://download.moodle.org/download.php/direct/stable36/moodle-latest-36.tgz
       dest: /var/www/html
       owner: apache
       group: apache
       remote_src: yes

   - name: Replace Document Root apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'DocumentRoot "/var/www/html"'
       replace: 'DocumentRoot "/var/www/html/moodle"'

   - name: Replace index apache config
     replace:
       path: /etc/httpd/conf/httpd.conf
       regexp: 'DirectoryIndex index.html'
       replace: 'DirectoryIndex index.php index.html index.htm'
      

   - name: Creates directory /var/moodledata
     file:
       path: /var/moodledata
       state: directory
       owner: apache
       group: apache
#       mode: 0755


   - name: Set httpd_can_network_connect flag on 
     seboolean:
       name: httpd_can_network_connect
       state: yes
       persistent: yes

  
   - name: Install Moodle
     command: php admin/cli/install.php
      --lang=en
      --dbtype=mariadb
      --wwwroot=http://35.188.93.113/
      --dataroot=/var/moodledata
      --dbhost=35.193.242.37
      --dbname=moodledb
      --dbuser=root
      --dbpass=moodle123
      --adminuser=admin
      --adminpass=Admin1
      --adminemail='example@example.com'
      --fullname='Moodle'
      --shortname=moodle
      --summary='Moodle'
      --non-interactive
      --allow-unstable
      --agree-license
#      --skip-database
     args:
       chdir: "/var/www/html/"
       creates: config.php
#     delegate_to: node1
     ignore_errors: yes
     notify:
       - restart httpd

   - name: Allow apache to modify files in /var/moodledata
     sefcontext:
       target: '/var/moodledata'
       setype: httpd_sys_rw_content_t
       reload: True
       state: present

   - name: Allow apache to modify files in /var/moodledata
     shell: chcon -R -t httpd_sys_rw_content_t /var/moodledata

   - name: Pushes configuration
     template: src=templates/config.php.j2 dest=/var/www/html/moodle/config.php mode=755 owner=apache group=apache
     notify:
       - restart httpd

